name: Validate Nix Flake

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

  workflow_run:
    workflows:
      - "Bump Flake Inputs"
    types:
      - completed

jobs:
  check-flake:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' || github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty

      - name: Check Flake
        run: nix flake check

      - name: Format Check
        run: nixpkgs-fmt --check .
